CUDA_VISIBLE_DEVICES='0' python3 main.py --dataset_name expressive_ta 
    --language ta \
    --dataset_path rasa/tamil/splits/1hr_happy \
    --wavs_path data/rasa/wavs-22k \
    --pretrained_checkpoint_path checkpoints/rasa/tamil/neutral/best_model.pth \
    --speaker all \
    --model fastpitch \
    --hidden_channels 512 \
    --use_speaker_embedding t \
    --use_language_embedding f \
    --use_d_vector_file f \
    --use_speaker_encoder_as_loss f \
    --use_ssim_loss f \
    --use_aligner t \
    --use_pre_computed_alignments f \
    --batch_size 32 \
    --batch_size_eval 32 \
    --batch_group_size 0 \
    --epochs 4000 \
    --aligner_epochs 4000 \
    --lr 0.0001 \
    --lr_scheduler NoamLR \
    --lr_scheduler_warmup_steps 50 \
    --num_workers 0 \
    --num_workers_eval 0 \
    --output_path rasa_tamil_1hr_happy \
    --run_description rasa_tamil_1hr_happy \
    --wandb_project_name rasa-tts 
